name: Run Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Set up Node.js & Install Allure CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g allure-commandline --save-dev

      - name: Run Tests
        run: mvn clean test -Dsuite=parallel -Dheadless=true

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
